# Generated by Django 4.1.1 on 2022-10-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='faculty',
            field=models.CharField(max_length=255),
        ),
    ]
