# Generated by Django 4.1.1 on 2022-10-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='goals',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VotingResult',
        ),
    ]
