# Generated by Django 4.1.1 on 2022-11-16 04:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_candidate_id_goals_candidate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('faculty', models.CharField(max_length=50)),
            ],
        ),
    ]
