# Generated by Django 4.1.1 on 2022-11-17 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_customuser_managers_alter_customuser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votings',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.faculty'),
        ),
    ]
