# Generated by Django 4.1.1 on 2022-12-03 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_votings_finish_votings_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='candidate_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.candidates'),
        ),
    ]
