# Generated by Django 4.1.1 on 2022-10-26 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VotingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.candidates')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='candidates',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.faculty'),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('is_voted', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=1000)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.faculty')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
