# Generated by Django 4.1.1 on 2022-11-10 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_candidates_goals_delete_votingresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='goals',
        ),
        migrations.CreateModel(
            name='Votings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_goals', models.IntegerField(default=0)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.candidates', unique=True)),
            ],
        ),
    ]
