# Generated by Django 4.1.1 on 2022-11-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_goals_candidate_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goals',
            old_name='candidate_id',
            new_name='candidate_name',
        ),
    ]
